export const AYAHAY_API_URL = process.env.NEXT_PUBLIC_API_V2_URL || "http://localhost:3000";

export const API_ENDPOINTS = {
	AUTH: "/bi/auth",
	OVERVIEW: "/bi/overview",
	SALES_REPORT: "/bi/sales-report",
	SALES_REPORT_ROUTES: "/bi/sales-report/routes",
	SALES_REPORT_EXPORT: "/bi/sales-report/export",
	SALES_REPORT_TEMPLATE: "/bi/sales-report/template",
	EXPENSES_REPORT: "/bi/expenses-report",
	EXPENSES_REPORT_EXPORT: "/bi/expenses-report/export",
	EXPENSES_REPORT_TEMPLATE: "/bi/expenses-report/template",
	EXPENSES_REPORT_IMPORT_PREVIEW: "/bi/expenses-report/import/preview",
	EXPENSES_REPORT_IMPORT_CONFIRM: "/bi/expenses-report/import/confirm",
	PASSENGERS_PER_TRIP: "/bi/passengers-per-trip",
	CARGO_PER_TRIP: "/bi/cargo-per-trip",
	STATUS_REPORT: "/bi/status-report",
	VESSELS_REPORT: "/bi/vessels-report",
	ADVANCE_BOOKING: "/bi/advance-booking",
	ROUTE_MAP: "/trips/unified",
	COMPARISON_TREND: "/bi/comparison-trend",
	COMPARISON_TREND_ENTITIES: "/bi/comparison-trend/entities",
	REVENUE_PER_BOOKINGS: "/bi/sales-report/revenue-per-bookings",
	SALES_REPORT_CHARTS: "/bi/sales-report/charts",
	RECENT_ACTIVITY: "/bi/recent-activity",
	TODAY_SCHEDULE: "/bi/today-schedule",
	CAPACITY_HEATMAP: "/bi/capacity-heatmap",
	TOP_AGENTS: "/bi/top-agents",
	ROUTE_SEA_PATHS: "/public/routes/sea-paths",
	OVERVIEW_FINANCE: "/bi/overview/finance",
} as const
