export const AYAHAY_API_URL = process.env.NEXT_PUBLIC_API_V2_URL || "http://localhost:3000";

export const API_ENDPOINTS = {
	AUTH: "/bi/auth",
	OVERVIEW: "/bi/overview",
	SALES_REPORT: "/bi/sales-report",
	SALES_REPORT_ROUTES: "/bi/sales-report/routes",
	SALES_REPORT_EXPORT: "/bi/sales-report/export",
	SALES_REPORT_TEMPLATE: "/bi/sales-report/template",
	EXPENSES_REPORT: "/bi/expenses-report",
	EXPENSES_REPORT_EXPORT: "/bi/expenses-report/export",
	EXPENSES_REPORT_TEMPLATE: "/bi/expenses-report/template",
	EXPENSES_REPORT_IMPORT_PREVIEW: "/bi/expenses-report/import/preview",
	EXPENSES_REPORT_IMPORT_CONFIRM: "/bi/expenses-report/import/confirm",
	PASSENGERS_PER_TRIP: "/bi/passengers-per-trip",
	CARGO_PER_TRIP: "/bi/cargo-per-trip",
	STATUS_REPORT: "/bi/status-report",
	VESSELS_REPORT: "/bi/vessels-report",
	ADVANCE_BOOKING: "/bi/advance-booking",
	ROUTE_MAP: "/trips/unified",
	COMPARISON_TREND: "/bi/comparison-trend",
	COMPARISON_TREND_ENTITIES: "/bi/comparison-trend/entities",
	REVENUE_PER_BOOKINGS: "/bi/sales-report/revenue-per-bookings",
	SALES_REPORT_CHARTS: "/bi/sales-report/charts",
	RECENT_ACTIVITY: "/bi/recent-activity",
	TODAY_SCHEDULE: "/bi/today-schedule",
	CAPACITY_HEATMAP: "/bi/capacity-heatmap",
	TOP_AGENTS: "/bi/top-agents",
	ROUTE_SEA_PATHS: "/public/routes/sea-paths",
	OVERVIEW_FINANCE: "/bi/overview/finance",

	// ── Analytics (Finance-Grade) ─────────────────────────────────────────────
	ANALYTICS_EXECUTIVE_OVERVIEW: "/bi/analytics/executive/overview",
	ANALYTICS_EXECUTIVE_KPIS: "/bi/analytics/executive/kpis",
	ANALYTICS_EXECUTIVE_FORECAST: "/bi/analytics/executive/forecast",
	ANALYTICS_FINANCIALS_REVENUE: "/bi/analytics/financials/revenue",
	ANALYTICS_FINANCIALS_PROFITABILITY: "/bi/analytics/financials/profitability",
	ANALYTICS_FINANCIALS_EXPENSES: "/bi/analytics/financials/expenses",
	ANALYTICS_FINANCIALS_RECONCILIATION: "/bi/analytics/financials/reconciliation",
	ANALYTICS_SALES_OVERVIEW: "/bi/analytics/sales/overview",
	ANALYTICS_SALES_CHANNELS: "/bi/analytics/sales/channels",
	ANALYTICS_SALES_INSIGHTS: "/bi/analytics/sales/insights",
	ANALYTICS_DEMAND_PASSENGERS: "/bi/analytics/demand/passengers",
	ANALYTICS_DEMAND_CARGO: "/bi/analytics/demand/cargo",
	ANALYTICS_DEMAND_TRENDS: "/bi/analytics/demand/trends",
	ANALYTICS_OPERATIONS_SCHEDULE: "/bi/analytics/operations/schedule",
	ANALYTICS_OPERATIONS_LIVE: "/bi/analytics/operations/live",
	ANALYTICS_ASSETS_VESSELS: "/bi/analytics/assets/vessels",
} as const
